baseURL = 'https://acdiost.github.io/'
languageCode = 'zh-Hans'
title = 'Dawn`s Blog'
theme = 'acdiost-theme'
publishDir = './docs'

[pagination]
pagerSize = 7

[params]
mainSections = ['posts']

[taxonomies]
category = 'categories'
tag = 'tags'
