# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Acdiost"
license = "MIT"
licenselink = "https://github.com/acdiost/acdiost.github.io/blob/main/LICENSE"
description = "Theme Acdiost with ChatGPT"
homepage = "https://acdiost.github.io/"
tags = ["blog", "responsive", "simple", "light", "clean", "tailwindcss"]
features = ["blog", "responsive", "simple", "light", "clean", "tailwindcss"]
min_version = "0.41.0"

[author]
  name = "acdiost"
  homepage = "https://acdiost.github.io/"

# If porting an existing theme
[original]
  name = "acdiost"
  homepage = "https://github.com/acdiost"
  repo = "https://github.com/acdiost/acdiost.github.io"
